[workspace]
members = ["bot-server", "mcserver-agent", "protocol"]
resolver = "3"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
protocol = { path = "protocol"}
serde_json = {version = "1"}