[workspace]
members = ["bot-server", "mcserver-agent", "protocal"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }